# Generated by Django 4.2.30 on 2026-05-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='watches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('title', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('machine', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
